In [6]:
import numpy as np
from scipy.ndimage import uniform_filter

np.set_printoptions(precision=4)

In [7]:
test = np.arange(1,10).reshape(3,3)

test_mask = np.zeros((9,9))

test_mask[3:-3, 3:-3] = test

In [8]:
test_mask

array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 2., 3., 0., 0., 0.],
       [0., 0., 0., 4., 5., 6., 0., 0., 0.],
       [0., 0., 0., 7., 8., 9., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [14]:
test_filter = uniform_filter(test_mask)

test_filter

array([[ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,
         0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00],
       [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,
         0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00],
       [ 0.0000e+00,  0.0000e+00,  1.1111e-01,  3.3333e-01,  6.6667e-01,
         5.5556e-01,  3.3333e-01,  0.0000e+00,  0.0000e+00],
       [ 0.0000e+00,  0.0000e+00,  5.5556e-01,  1.3333e+00,  2.3333e+00,
         1.7778e+00,  1.0000e+00, -1.4803e-16, -1.4803e-16],
       [ 0.0000e+00,  0.0000e+00,  1.3333e+00,  3.0000e+00,  5.0000e+00,
         3.6667e+00,  2.0000e+00,  0.0000e+00,  0.0000e+00],
       [ 0.0000e+00,  0.0000e+00,  1.2222e+00,  2.6667e+00,  4.3333e+00,
         3.1111e+00,  1.6667e+00,  2.9606e-16,  2.9606e-16],
       [ 0.0000e+00,  0.0000e+00,  7.7778e-01,  1.6667e+00,  2.6667e+00,
         1.8889e+00,  1.0000e+00, -1.4803e-16, -1.4803e-16],
       [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0

In [15]:
bg_mask = np.zeros((9,9))

bg_mask[3:-3, 3:-3] = 1

bg_mask

array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 1., 1., 0., 0., 0.],
       [0., 0., 0., 1., 1., 1., 0., 0., 0.],
       [0., 0., 0., 1., 1., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [17]:
weights = uniform_filter(bg_mask)

weights

array([[0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
        0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
       [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
        0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
       [0.0000e+00, 0.0000e+00, 1.1111e-01, 2.2222e-01, 3.3333e-01,
        2.2222e-01, 1.1111e-01, 3.7007e-17, 3.7007e-17],
       [0.0000e+00, 0.0000e+00, 2.2222e-01, 4.4444e-01, 6.6667e-01,
        4.4444e-01, 2.2222e-01, 7.4015e-17, 7.4015e-17],
       [0.0000e+00, 0.0000e+00, 3.3333e-01, 6.6667e-01, 1.0000e+00,
        6.6667e-01, 3.3333e-01, 0.0000e+00, 0.0000e+00],
       [0.0000e+00, 0.0000e+00, 2.2222e-01, 4.4444e-01, 6.6667e-01,
        4.4444e-01, 2.2222e-01, 7.4015e-17, 7.4015e-17],
       [0.0000e+00, 0.0000e+00, 1.1111e-01, 2.2222e-01, 3.3333e-01,
        2.2222e-01, 1.1111e-01, 3.7007e-17, 3.7007e-17],
       [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
        0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],


In [19]:
np.where(weights > 0.016, test_filter / weights, 0)

C:\Users\Jonny\AppData\Local\Temp\ipykernel_19648\2036960033.py:1: RuntimeWarning: invalid value encountered in divide
  np.where(weights > 0.016, test_filter / weights, 0)


array([[0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ],
       [0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ],
       [0. , 0. , 1. , 1.5, 2. , 2.5, 3. , 0. , 0. ],
       [0. , 0. , 2.5, 3. , 3.5, 4. , 4.5, 0. , 0. ],
       [0. , 0. , 4. , 4.5, 5. , 5.5, 6. , 0. , 0. ],
       [0. , 0. , 5.5, 6. , 6.5, 7. , 7.5, 0. , 0. ],
       [0. , 0. , 7. , 7.5, 8. , 8.5, 9. , 0. , 0. ],
       [0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ],
       [0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ]])